[package]
name = "armv5te_demo"
version = "0.1.0"
authors = ["Philip Z <philip_chang@163.com>"]


[dependencies]



[profile.release]
panic = "abort"
strip = true


[profile.dev]
debug = true
panic = "abort"
